# Numpy 
Numpy is a general purpose array-processing package.It provides high performance multidimensinal array object, and tools for working with these arrays. It is fundamental package for scientific computing with Python.

# what is an array
An array is data structure that stores the value of same data type. In python, lot of people confuse with array and lists. Array is a data structure that contains same datatype but list can contain different datatypes.

In [1]:
import numpy as np 
# we need to import numpy to preprocess arrays.
#Arrays are widely used in datascience so they created a library to make use of arrays easily.

In [2]:
array1=[1,2,3,4,5]
#this is an one-dimensinal array.
arr=np.array(array1)

In [3]:
type(arr)
# to know the type of the array
#ndarray means N-dimensinal Array

numpy.ndarray

In [7]:
array2=[[2,6,8,9,3],
         [3,5,78,8,3]]

In [14]:
type(array2)
# this is not n-dimensinal array because it is assigined np.array like in previous line.

list

In [15]:
arr.shape
#It gives the shape of the array it can only be used for arrays not for the list datatype.

(5,)

In [16]:
array2.shape
#list datatype does not have shape only arrays have

AttributeError: 'list' object has no attribute 'shape'

In [25]:
array3=[[1,3,4],
       [4,5,7],
       [6,0,8],
       [2,8,6]]
arr1=np.array(array3) # this line is to convert list into array datatype


In [26]:
arr1.shape

(4, 3)

# Reshaping is same as transposing(but u can reshape them into any number of rows or columns you like) the matrix.
There are certain rules to transpose a matrix 
#1 The number of elements in the martix should be proportinal to the shape of the new matrix.

In [28]:
arr1.reshape(3,4)

array([[1, 3, 4, 4],
       [5, 7, 6, 0],
       [8, 2, 8, 6]])

In [29]:
arr1.reshape(1,12)

array([[1, 3, 4, 4, 5, 7, 6, 0, 8, 2, 8, 6]])

In [31]:
arr1.reshape(2,6)

array([[1, 3, 4, 4, 5, 7],
       [6, 0, 8, 2, 8, 6]])

# Indexing.
This is the process of accessing an element from an array.

In [32]:
arr4=np.array([1,5,3,89,7,82,20,5])

In [33]:
arr4[0]

1

In [57]:
Matrix=[[1,2,3,8],
        [5,9,6,6],
        [9,5,3,9],
        [2,9,7,7,]]
arr=np.array(Matrix)

In [56]:
arr[0:4,0:3]
# Here 0:4 represents columns and 0:3 represents rows.
# By typing the comand we are just selecting the columns(0 to 4) and in the row(0 to 3)


array([[1, 2, 3],
       [5, 9, 6],
       [9, 5, 3],
       [2, 9, 7]])

In [58]:
# TO pick up 3977 from the matrix
arr[2:4,2:4]

array([[3, 9],
       [7, 7]])

In [63]:
arr=np.arange(0,10,step=3)
#arange keyword creates 1-D array.
#step creates the gap between 1-D array.
print(arr)

[0 3 6 9]


In [66]:
np.linspace(1,10,10)
#In linspace that it creates sequences of evenly spaced numbers structured as a NumPy array.

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10.])

In [67]:
#copy function.
#This function creates copies of anything that you need to add in the array.
arr

array([0, 3, 6, 9])

In [74]:
arr[4:]=500
print(arr)

[  0   3   6 500]


In [75]:
# Through this we can check the conditions inside the array also.
var=2
arr<2

array([ True, False, False, False])

In [76]:
arr*3
# we can also do multiplication. 

array([   0,    9,   18, 1500])

In [77]:
arr/2
# we can also do division.

array([  0. ,   1.5,   3. , 250. ])

In [81]:
np. ones(2)
# this function is to convert all the elements in the array to ones.

array([1., 1.])

In [87]:
# This function selects random function from the given shape of the matrix or array.
np.random.rand(3,3)
# Here the given shape is (3,3)

array([[0.61009517, 0.79791119, 0.86987266],
       [0.0509652 , 0.48563855, 0.98152046],
       [0.07857279, 0.18812648, 0.67427158]])

In [89]:
arr_ex=np.random.randn(4,4)
# here randn selects the normal distribution based on the standard normal distribution.
arr_ex

array([[-2.61584378,  0.90957523, -0.03616907,  0.78583208],
       [-0.76079706, -0.62667642, -0.67359672, -0.03881678],
       [ 1.09137044, -0.07690355, -0.11155831, -0.71315388],
       [ 0.89874886,  2.03591731, -1.76006845,  1.25778347]])